spring:
  application:
    name: eureka
server:
  port: 10001

eureka:
  instance:
    hostname: pro
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
     defaultZone:  http://dev:9001/eureka/