spring:
  application:
    name: mq2
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.cloud.openfeign: debug

server:
  port: 9004




