server:
  port: 9002

spring:
#  cloud:
#    gateway:
#      routes:
#       -id: neo_route
#        uri: http://www.baidu.com
#        predlicates:
#        -Path=/spring-cloud
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka

