spring:
  application:
    name: consumer
server:
  port: 9004

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka

feign:
  hystrix:
    enabled: true


# failed opening connection to hystrix.stream 404 http/1.1 404
management:
  endpoints:
    web:
      exposure:
#        include: ["hystrix.stream","actuator/hystrix.stream"]
#        include: ["actuator/hystrix.stream"]
        include: "*"
#      base-path: /
